# Generated by Django 2.1.5 on 2019-01-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(blank=True, to='homepage.Category'),
        ),
    ]
