# Generated by Django 2.1.5 on 2019-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190127_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='views',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
