# Generated by Django 2.1.5 on 2019-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_posts_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='views',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
    ]
